import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// import { SessionProvider as Provider } from "next-auth/react";
import Provider from "./components/Provider";
// import { signOut, useSession } from "next-auth/react";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* header */}
        <Header />
        <hr />
        <main>
          <Provider>{children}</Provider>
        </main>
        {/* footer  */}
      </body>
    </html>
  );
}
